#pragma once
#include "GlidManager.h"
enum IMAGE_LIST {
	IMAGE_STAGE1,	//	ステージの背景
	IMAGE_STAGE2,
	IMAGE_STAGE3,
	IMAGE_STAGE4,
	IMAGE_STAGE5,
	IMAGE_STAGE6,
	IMAGE_STAGE7,
	IMAGE_STAGE8,
	IMAGE_STAGE9,
	IMAGE_WALL_STAGE1,
	IMAGE_WALL_STAGE2,
	IMAGE_WALL_STAGE3,
	IMAGE_WALL_STAGE4,
	IMAGE_WALL_STAGE5,
	IMAGE_WALL_STAGE6,
	IMAGE_WALL_STAGE7,
	IMAGE_WALL_STAGE8,
	IMAGE_WALL_STAGE9,
	IMAGE_SHUTTER_STAGE1,
	IMAGE_SHUTTER_STAGE2,
	IMAGE_SHUTTER_STAGE3,
	IMAGE_SHUTTER_STAGE4,
	IMAGE_SHUTTER_STAGE5,
	IMAGE_SHUTTER_STAGE6,
	IMAGE_SHUTTER_STAGE7,
	IMAGE_SHUTTER_STAGE8,
	IMAGE_SHUTTER_STAGE9,
	IMAGE_ALLOW,	//	プレイヤーの画像
	IMAGE_RED_IDLE,
	IMAGE_RED_LUMINUS,
	IMAGE_RED_POP,
	IMAGE_GREEN_IDLE,
	IMAGE_GREEN_LUMINUS,
	IMAGE_GREEN_POP,
	IMAGE_BLUE_IDLE,
	IMAGE_BLUE_LUMINUS,
	IMAGE_BLUE_POP,
	IMAGE_YELLOW_IDLE,
	IMAGE_YELLOW_LUMINUS,
	IMAGE_YELLOW_POP,
	IMAGE_PURPLE_IDLE,
	IMAGE_PURPLE_LUMINUS,
	IMAGE_PURPLE_POP,
	IMAGE_WHITE_IDLE,
	IMAGE_WHITE_LUMINUS,
	IMAGE_WHITE_POP,
	IMAGE_BLACK_IDLE,
	IMAGE_BLACK_LUMINUS,
	IMAGE_BLACK_POP,
	IMAGE_ORANGE_IDLE,
	IMAGE_ORANGE_LUMINUS,
	IMAGE_ORANGE_POP,
	IMAGE_MONSTER_RED,
	IMAGE_MONSTER_GREEN,
	IMAGE_MONSTER_BLUE,
	IMAGE_MONSTER_YELLOW,
	IMAGE_MONSTER_PURPLE,
	IMAGE_MONSTER_WHITE,
	IMAGE_MONSTER_BLACK,
	IMAGE_MONSTER_ORANGE,
	IMAGE_LEFT_BABBLEN,
	IMAGE_RIGHT_BABBLEN,
	IMAGE_NEXT,
	IMAGE_LAUNCHER_BASE,
	IMAGE_LAUNCHER_PIPE,
	IMAGE_BAR,
	IMAGE_ROUNDBOARD,
	IMAGE_NUMBER,
	IMAGE_NUMBER_REVERSE,
	IMAGE_SCORE_NUMBER,
	IMAGE_TITLE_BG,
	IMAGE_TITLE_BABBLEN,
	IMAGE_TITLE_BOBBLEN,
	IMAGE_ROUND_CLEAR,
	IMAGE_BUBBLE_GRAY,
	IMAGE_ENDING1,
	IMAGE_ENDING2,
	IMAGE_ENDING3,
	IMAGE_ENDING_HOUSE,
	IMAGE_CLEAR,
	IMAGE_STAR,
	IMAGE_STAR_WALL,
	IMAGE_STAR_SHUTTER,
	IMAGE_GLASS,
	IMAGE_GAMEOVER,
	IMAGE_SEC,
	IMAGE_PTS,
	IMAGE_MAX,
};


class ImageManager
{
	public:
		static ImageManager& GetInstance();
	private:
		ImageManager();
		~ImageManager();
		ImageManager(const ImageManager&) = delete;
		ImageManager& operator=(const ImageManager&) = delete;

		int images[IMAGE_MAX];	//	画像のハンドルを入れる配列
public:
	int GetImage(int num) const { return images[num]; }
	int GetPopImage(int state);
	int GetMonsterImage(int state);
	int GetBubbleImage(int state);
	int GetLuminusImage(int state);
};